import Head from 'next/head';
// import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState('');

  async function runQuery() {
    const options = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(query),
    };

    const res = await fetch('/api/translate', options);
    const data = await res.json();

    setResponse(data.sql);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <input value={query} onChange={e => setQuery(e.target.value)} />
        <p>{response || 'Translating...'}</p>
        <button onClick={runQuery}>Run Query</button>
      </main>
    </>
  );
}
